### ISSUE TITLE
TclError

### ISSUE THREAD

**Issue by seyyedaliayati** [stephen70/Chess-Coordinate-Trainer#5]
`python3 Chess\ Coordinate\ Trainer.py 
Traceback (most recent call last):
  File "Chess Coordinate Trainer.py", line 81, in <module>
    top.wm_iconbitmap(windowIconPath)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1871, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "Icons/CCT.ico" not defined
`

**Comment by stephen70** [comment]
Please extract the folder from the zip before running, as otherwise the icons will not be found.
